routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/how-it-works', 'HomeController@about');
Route::get('/become-a-partner', 'HomeController@becomePartner');
Route::post('/partnership-submission','HomeController@partnershipSubmission');
Route::get('/partner/{alias}','HomeController@partner');


Route::get('/profile','Frontend\UserController@index')->name('user.profile');
Route::get('/cprofile/referal','Frontend\Consultancy\ConsultancyController@referal');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/test', 'HomeController@index');

Route::post('/subscribe','HomeController@subscribe')->name('subscribe');
Route::get('unsubscribe/{token}','HomeController@unsubscribe')->name('unsubscribe');
Route::post('unsubscribe/{token}','HomeController@unsubscribed')->name('unsubscribed');

Route::get('/contact-us', 'HomeController@contactPage')->name('contact-us');
Route::post('/contact-us','HomeController@contactUs');

Route::get('/notifications','HomeController@notifications');

Route::prefix('consultancy')->group(function(){
    Route::get('/login','Frontend\Consultancy\Auth\LoginController@showLoginForm')->name('consultancy_login');
	Route::post('/login','Frontend\Consultancy\Auth\LoginController@login');
	Route::post('/logout','Frontend\Consultancy\Auth\LoginController@logout')->name('consultancy_logout');
	Route::post('/password/email','Frontend\Consultancy\Auth\ForgotPasswordController@sendResetLinkEmail')->name('consultancy_password.email');
	Route::post('/password/reset','Frontend\Consultancy\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Frontend\Consultancy\Auth\ForgotPasswordController@showLinkRequestForm')->name('consultancy_password.request');
	Route::get('/password/reset/{token}','Frontend\Consultancy\Auth\ResetPasswordController@showResetForm')->name('consultancy_password.reset');
    
    // Route::get('profile','Frontend\Consultancy\ProfileController@index');
    // Route::post('profile/changePassword','Frontend\Consultancy\ProfileController@changePassword')->name('consultancy.changePassword');
    // Route::post('profile/changeName','Frontend\Consultancy\ProfileController@updateName')->name('consultancy.updateName');

    Route::get('/cprofile','Frontend\Consultancy\ConsultancyController@index')->name('consultancy.profile');
    Route::get('/editprofile','Frontend\Consultancy\ConsultancyController@editProfile');
    Route::post('changepassword','Frontend\Consultancy\ConsultancyController@changePassword')->name('consultancy.changePassword');
   
    Route::get('/cprofile/referal','Frontend\Consultancy\ConsultancyController@referal');  
    Route::post('/referal/togglestatus','Frontend\Consultancy\ConsultancyController@toggleStatus');  
    Route::post('/referal/submitreceipt','Frontend\Consultancy\ConsultancyController@submitReceipt');  
          
    Route::get('/dashboard','Frontend\Consultancy\ConsultancyController@dashboard');
    Route::post('/dashboard/savecommission','Frontend\Consultancy\ConsultancyController@saveCommission');
    Route::post('/dashboard/toggleshowrate','Frontend\Consultancy\ConsultancyController@toggleShowRate');
    
    
    
});

Route::prefix('user')->group(function(){
    Auth::routes();
    Route::get('/register/getEmail',function(){
        return redirect('user/login');
    });

    Route::get('/editprofile','Frontend\UserController@editProfile');
    
    
    Route::post('/register/getEmail','Auth\RegisterController@setEmail')->name('set_email');
    Route::get('confirm/resend','Auth\RegisterController@resendConfirmation')->name('resend_confirmation');
    Route::get('confirm/{token}','Auth\RegisterController@confirmEmail')->name('confirmEmail');

    // Route::get('/profile','Frontend\UserController@index')->name('user.profile');

    Route::post('/changeprofilepicture','Frontend\UserController@changeProfilePicture');
    Route::get('/getreferal','Frontend\UserController@getReferal');    
    Route::post('/submitreferal','Frontend\UserController@submitReferal');
    Route::post('/savereferal','Frontend\UserController@saveReferal');
    Route::post('/submitreferaledit','Frontend\UserController@submitEditedReferal');
    Route::post('/savereferaledit','Frontend\UserController@saveEditedReferal');
    Route::post('/deletereferal','Frontend\UserController@deleteReferal');
    Route::post('/saveinfo','Frontend\UserController@saveInfo');
    Route::get('/getcommission','Frontend\UserController@getCommission');    
    Route::post('profile/changepassword','Frontend\UserController@changePassword')->name('user.changePassword');
});
Route::get('signin/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('signin/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::resource('categories', 'Admin\CategoryController',['except' => ['create','edit','show']]);

    Route::resource('partners', 'Admin\PartnerController',['except' => ['create','show']]);

    Route::resource('partners/{partner_id}/branches', 'Admin\BranchController',['except' => ['create','show']]);

    Route::get('users','Admin\UserController@index')->name('users.index');

    Route::get('referals','Admin\ReferalController@index')->name('referals.index');
    Route::post('referals/verifyreceipt','Admin\ReferalController@verifyReceipt');
    Route::post('referals/rejectreceipt','Admin\ReferalController@rejectReceipt');
    Route::post('referals/markaspaid','Admin\ReferalController@markAsPaid');
    

    // Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    // Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    // Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    // Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    // Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    // Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    // Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    // Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

    Route::get('partnerships/unseen','Admin\PartnershipController@unseenMsg')->name('partnerships.unseen');    
    Route::resource('partnerships', 'Admin\PartnershipController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenPartnershipsCount','Admin\PartnershipController@getUnseenMsgCount')->name('getUnseenPartnershipCount');
    Route::get('getUnseenPartnershipsMsg','Admin\PartnershipController@getUnseenMsg')->name('getUnseenPartnership');

    Route::get('getUnseenNotificationCount','Admin\NotificationController@getUnseenMsgCount')->name('getUnseenNotificationCount');
    Route::get('getUnseenNotificationMsg','Admin\NotificationController@getUnseenMsg')->name('getUnseenNotification');
    Route::get('/notifications/view','Admin\NotificationController@viewNotification');
    Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');
    // Route::post('test','Admin\AdminController@test')->name('test');

    Route::get('/','Admin\AdminController@index');
});

Route::get('/asset/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    $ext = explode(".",$img);
    $ext = end($ext);

app/Partnership.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Partnership extends Model
{
    //
}

app/Http/Controllers/Admin/PartnershipController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Rules\NoEmptyContent;
use Mail;
use App\Partnership;
use Auth;
class PartnershipController extends Controller
{
    public function __construct(Request $request)
    {
        $this->middleware('auth:admin_user');
    }

    public function index(){
        $contact_messages = Partnership::orderBy('created_at','desc')->paginate(10);
        return view('admin.partnerships.index')->with('contacts',$contact_messages)->with('state','all');
    }

    public function unseenMsg(){
        $contact_messages = Partnership::where('seen','0')->orderBy('created_at','desc')->paginate(10);
        return view('admin.partnerships.index')->with('contacts',$contact_messages)->with('state','unseen');
    }

    public function show($id)
    {
        $Contact = Partnership::find($id);

        if(!$Contact)
            abort(404);

        if(!$Contact->seen){
            $Contact->seen = 1;
            $Contact->save();
        }
        
        return view('admin.partnerships.show')->with('contact',$Contact);
    }

    public function destroy($id,Request $request)
    {
        $Contact = Partnership::find($id);
        if(!$Contact)
            abort(404);
        $Contact->delete();

        $request->session()->flash('success', 'Message deleted');
        return redirect()->route('contact-us-messages.index');
    }


    public function getUnseenMsgCount(Request $request){
        
        if ($request->ajax()){
            $mno = Partnership::where('seen','0')->count();
            return response()->json(['mno' => $mno]);
        }
        abort(404);  
    }

    public function getUnseenMsg(Request $request){
        if ($request->ajax()){
            $messages = Partnership::where('seen','0')->latest()->limit(5)->get();
            $mno = Partnership::where('seen','0')->count();
            $view = view('admin.partials.pnotis')->with('messages',$messages)->with('mno',$mno)->render();
            
            return response()->json(['html' => $view, 'mno' => $mno]);
        }
        abort(404);
    }
}

resources/views/admin/partnerships/index.blade.php
 @extends('layouts.admin')

 @section('body')

    <div class="content-header row">
    </div>
    <div class="content-body">
        <div class="text-xs-right">
            @if($state == 'all')
                <a class="btn btn-primary btn-min-width mr-1 mb-1 " href="{{ route('partnerships.unseen') }}">See all unseen messages</a>
            @else
                <a class="btn btn-primary btn-min-width mr-1 mb-1 " href="{{ route('partnerships.index') }}">See all messages</a>
            @endif
        </div>
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Partnership Inquiries</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Partner_type</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($contacts as $contact)
                                @if(!$contact->seen && $state == 'all')
                                    <tr style="background:#d6d3d3">
                                @else
                                    <tr>
                                @endif
                                    <th scope="row">{{ $loop->iteration }}</th>
                                    <td>{{ $contact->buisness_name }}</td>
                                    <td>{{ $contact->partner_type }}</td>
                                    <td>
                                        <a class="btn btn-outline-info btn-sm" title="View" href="{{ route('partnerships.show',$contact->id) }}"><i class="icon-eye"></i></a>
                
                                        <form action="{{ route('partnerships.destroy',$contact->id) }}" method="POST" style="display:inline">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE" >

                                            <button id='deleteContact' title="delete" type="button" class="btn btn-outline-danger btn-sm"><i class="icon-trash-o"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        @if(count($contacts)==0)
                            <p class="font-medium-3 text-muted text-xs-center" style="margin:100px">No {{ $state == 'all'?'':'New'}} Messages</p>
                        @endif
                        <div class="text-xs-center mb-3">
                            <nav aria-label="Page navigation">
                                {{ $contacts->links('admin.partials.pagination') }}
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
@endsection

resources/views/admin/partnerships/show.blade.php
 @extends('layouts.admin')

@section('body')

    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Message #{{ $contact->id }}</h2>
        </div>
        <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
            <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                    <a class="btn btn-primary btn-min-width mr-1 mb-1 " href="{{ route('contact-us-messages.index') }}">See all messages</a>
                </ol>
            </div>
        </div>
    </div>
    <div class="content-body">
        <section class="card">
            <div id="invoice-template" class="card-block">
                <!-- Invoice Company Details -->
                <div id="invoice-company-details" class="row">
                    <div class="col-md-6 col-sm-12 text-xs-center text-md-left">
                        <ul class="px-0 list-unstyled">
                            <li><strong>Buisness Name      : </strong>{{ $contact->buisness_name }}</li>
                            <li><strong>Locations      : </strong>{!! $contact->locations !!}</li>

                            <li><strong>Contact Name      : </strong>{{ $contact->contact_name }}</li>

                            <li><strong>Contact Position     : </strong>{{ $contact->contact_position }}</li>                                
                            <li><strong>Tel No. : </strong>{{ $contact->tel_no }}</li><br>
                            <li><strong>Mobile No. : </strong>{{ $contact->mobile_no }}</li><br>
                            

                            <li><span class="text-muted">Received Date :</span> {{ date('M j, Y', strtotime($contact->created_at)) }}</li>
                        </ul>
                    </div>
                </div>
                <!--/ Invoice Company Details -->

                <!-- Invoice Footer -->
                <div id="invoice-items-details" class="pt-2">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="text-xs-center">
                                <strong>Partnership Type : </strong>{{ $contact->partner_type }}
                            </div><br>
                            <p class="lead">Agreed Commission Structure:</p>
                            @if($contact->partner_type=='Gym')
                            <p>1 Month membership (per referral): {{ $contact->gym_1 }}</p>
                            <p>6 Month membership (per referral): {{ $contact->gym_2 }}</p>
                            @elseif($contact->partner_type=='Cons')
                            <p>VET course (per referral): {{ $contact->cons_1 }}</p>
                            <p>University/College Course (per referral): {{ $contact->cons_2 }}</p>
                            @elseif($contact->partner_type=='Tut')
                            <p>Tuitions/PTE/IELTS/PY: (per referral): {{ $contact->tut_1 }}</p>
                            @elseif($contact->partner_type=='Real')
                            <p>Percentage (per referral): {{ $contact->real_1 }}</p>
                            @endif
                        </div>
                    </div>
                </div>
                <!--/ Invoice Footer -->

            </div>
        </section>
    </div>

@endsection