routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/how-it-works', 'HomeController@about');
Route::get('/become-a-partner', 'HomeController@becomePartner');
Route::post('/partnership-submission','HomeController@partnershipSubmission');
Route::get('/partner/{alias}','HomeController@partner');


Route::get('/profile','Frontend\UserController@index')->name('user.profile');
Route::get('/cprofile/referal','Frontend\Consultancy\ConsultancyController@referal');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/test', 'HomeController@index');

Route::post('/subscribe','HomeController@subscribe')->name('subscribe');
Route::get('unsubscribe/{token}','HomeController@unsubscribe')->name('unsubscribe');
Route::post('unsubscribe/{token}','HomeController@unsubscribed')->name('unsubscribed');

Route::get('/contact-us', 'HomeController@contactPage')->name('contact-us');
Route::post('/contact-us','HomeController@contactUs');

Route::get('/notifications','HomeController@notifications');

Route::prefix('consultancy')->group(function(){
    Route::get('/login','Frontend\Consultancy\Auth\LoginController@showLoginForm')->name('consultancy_login');
	Route::post('/login','Frontend\Consultancy\Auth\LoginController@login');
	Route::post('/logout','Frontend\Consultancy\Auth\LoginController@logout')->name('consultancy_logout');
	Route::post('/password/email','Frontend\Consultancy\Auth\ForgotPasswordController@sendResetLinkEmail')->name('consultancy_password.email');
	Route::post('/password/reset','Frontend\Consultancy\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Frontend\Consultancy\Auth\ForgotPasswordController@showLinkRequestForm')->name('consultancy_password.request');
	Route::get('/password/reset/{token}','Frontend\Consultancy\Auth\ResetPasswordController@showResetForm')->name('consultancy_password.reset');
    
    // Route::get('profile','Frontend\Consultancy\ProfileController@index');
    // Route::post('profile/changePassword','Frontend\Consultancy\ProfileController@changePassword')->name('consultancy.changePassword');
    // Route::post('profile/changeName','Frontend\Consultancy\ProfileController@updateName')->name('consultancy.updateName');

    Route::get('/cprofile','Frontend\Consultancy\ConsultancyController@index')->name('consultancy.profile');
    Route::get('/editprofile','Frontend\Consultancy\ConsultancyController@editProfile');
    Route::post('changepassword','Frontend\Consultancy\ConsultancyController@changePassword')->name('consultancy.changePassword');
   
    Route::get('/cprofile/referal','Frontend\Consultancy\ConsultancyController@referal');  
    Route::post('/referal/togglestatus','Frontend\Consultancy\ConsultancyController@toggleStatus');  
    Route::post('/referal/submitreceipt','Frontend\Consultancy\ConsultancyController@submitReceipt');  
          
    Route::get('/dashboard','Frontend\Consultancy\ConsultancyController@dashboard');
    Route::post('/dashboard/savecommission','Frontend\Consultancy\ConsultancyController@saveCommission');
    Route::post('/dashboard/toggleshowrate','Frontend\Consultancy\ConsultancyController@toggleShowRate');
    
    
    
});

Route::prefix('user')->group(function(){
    Auth::routes();
    Route::get('/register/getEmail',function(){
        return redirect('user/login');
    });

    Route::get('/editprofile','Frontend\UserController@editProfile');
    
    
    Route::post('/register/getEmail','Auth\RegisterController@setEmail')->name('set_email');
    Route::get('confirm/resend','Auth\RegisterController@resendConfirmation')->name('resend_confirmation');
    Route::get('confirm/{token}','Auth\RegisterController@confirmEmail')->name('confirmEmail');

    // Route::get('/profile','Frontend\UserController@index')->name('user.profile');

    Route::post('/changeprofilepicture','Frontend\UserController@changeProfilePicture');
    Route::get('/getreferal','Frontend\UserController@getReferal');    
    Route::post('/submitreferal','Frontend\UserController@submitReferal');
    Route::post('/savereferal','Frontend\UserController@saveReferal');
    Route::post('/submitreferaledit','Frontend\UserController@submitEditedReferal');
    Route::post('/savereferaledit','Frontend\UserController@saveEditedReferal');
    Route::post('/deletereferal','Frontend\UserController@deleteReferal');
    Route::post('/saveinfo','Frontend\UserController@saveInfo');
    Route::get('/getcommission','Frontend\UserController@getCommission');    
    Route::post('profile/changepassword','Frontend\UserController@changePassword')->name('user.changePassword');
});
Route::get('signin/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('signin/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::resource('categories', 'Admin\CategoryController',['except' => ['create','edit','show']]);

    Route::resource('partners', 'Admin\PartnerController',['except' => ['create','show']]);

    Route::resource('partners/{partner_id}/branches', 'Admin\BranchController',['except' => ['create','show']]);

    Route::get('users','Admin\UserController@index')->name('users.index');

    Route::get('referals','Admin\ReferalController@index')->name('referals.index');
    Route::post('referals/verifyreceipt','Admin\ReferalController@verifyReceipt');
    Route::post('referals/rejectreceipt','Admin\ReferalController@rejectReceipt');
    Route::post('referals/markaspaid','Admin\ReferalController@markAsPaid');
    

    // Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    // Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    // Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    // Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    // Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    // Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    // Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    // Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

    Route::get('partnerships/unseen','Admin\PartnershipController@unseenMsg')->name('partnerships.unseen');    
    Route::resource('partnerships', 'Admin\PartnershipController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenPartnershipsCount','Admin\PartnershipController@getUnseenMsgCount')->name('getUnseenPartnershipCount');
    Route::get('getUnseenPartnershipsMsg','Admin\PartnershipController@getUnseenMsg')->name('getUnseenPartnership');

    Route::get('getUnseenNotificationCount','Admin\NotificationController@getUnseenMsgCount')->name('getUnseenNotificationCount');
    Route::get('getUnseenNotificationMsg','Admin\NotificationController@getUnseenMsg')->name('getUnseenNotification');
    Route::get('/notifications/view','Admin\NotificationController@viewNotification');
    Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');
    // Route::post('test','Admin\AdminController@test')->name('test');

    Route::get('/','Admin\AdminController@index');
});

Route::get('/asset/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    $ext = explode(".",$img);
    $ext = end($ext);

resources/views/admin/categories.blade.php
@extends('layouts.admin')

@section('body')
       
    <div class="content-body">
        <section id="addcategories">  
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title" ><a data-action="collapse"><h3>Categories</h3><h6>Add, Edit or Remove Categories</h6>  </a></div>
                            <a class="heading-elements-toggle">
                                <i class="icon-ellipsis font-medium-3"></i>
                            </a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body"> <!-- // collapse -->
                            <div class="card-block">
                                <div class="row col-md-12">
                                    <div style="padding-bottom:20px;">
                                        <form class="form" method="POST" action="{{ route('categories.store') }}">
                                            {{ csrf_field() }}
                                            <div class="row">
                                                <div class="form-body">
                                                    <div class="form-group col-sm-3">
                                                        <input type="text" class="form-control" placeholder="Add New Category" name="title" required>
                                                    </div>

                                                    <div class="form-group  col-sm-3">
                                                        <button type="submit" class="btn btn-primary">
                                                            <i class="icon-check2">Add Category</i> 
                                                        </button>
                                                    </div>  
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        @if(count($categories) == 0)
                                            <h6 style="text-align:  center;margin: 50px;">No category added yet.</h6>
                                        @else
                                            <div class="table-responsive ">
                                                
                                                <table class="table table-bordered">
                                                    <thead>
                                                        <tr>
                                                            <th style="width: 40%">Category</th>
                                                            <th style="width: 20%">Actions</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach($categories as $c)
                                                            <tr>
                                                                <td class="text-middle">
                                                                    <h4 id="categoryName{{ $c->id }}">{{$c->title}} </h4>
                                                                    
                                                                    <div id="CatupdateDiv{{$c->id}}" hidden>
                                                                        <form class="form" method="POST" action="{{ route('categories.update',$c->id) }}">
                                                                            <div class="row form-body">
                                                                                <div class="form-group col-sm-6">
                                                                                    {{csrf_field()}}
                                                                                    <input hidden name="_method" value="PATCH">

                                                                                    <input type="text" class="form-control" placeholder="Edit Name" name="title" value="{{ $c->title }}" required> 
                                                                                </div>
                                                                                <div class="form-group col-sm-6">
                                                                                    <button type="submit" class="btn btn-blue"> 
                                                                                        <i class="icon-check2"></i> 
                                                                                    </button>

                                                                                    <button class="btn btn-red" type="button" id="Catcancel{{ $c->id }}">
                                                                                        <i class="icon-cross"></i>
                                                                                    </button>          
                                                                                </div>
                                                                            </div> 
                                                                        </form>
                                                                    </div>
                                                                </td>
                                                                
                                                                <td class="text-middle">
                                                                    <a href="javascript:void(0)"  class="btn btn-outline-warning" style="" id="Catedit{{ $c->id }}">Edit</a>
                                                                
                                                                    <form action="{{ route('categories.destroy',$c->id) }}" method="POST" style="display:inline">
                                                                        {{ csrf_field() }}
                                                                        <input hidden name="_method" value="DELETE"/>
                                                                        <button type="button" id="deleteCat{{ $c->id }}" class="btn btn-outline-danger">Delete</button>
                                                                    </form>

                                                                </td>
                                                            </tr>
                                                        @endforeach
                                                    </tbody>
                                                </table>
                                                
                                            </div>
                                        @endif
                                        <div class="text-xs-center mb-3">
                                            <nav aria-label="Page navigation">
                                                {{ $categories->links('admin.partials.pagination') }}
                                            </nav>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection

@section('js')

<script type="text/javascript">
    $(document).ready(function() {
        $("[id*='Catedit']").click(function(){
            var id = $(this).attr("id").slice(7);
            $('#categoryName'+id).attr("hidden","true");
            $("#CatupdateDiv"+id).removeAttr("hidden");
        });

        $("[id*='Catcancel']").click(function(){
            var id = $(this).attr("id").slice(9);
            $('#categoryName'+id).removeAttr("hidden");
            $("#CatupdateDiv"+id).attr("hidden","true");
        });
    });
</script>
@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('body')
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Dashboard</h2>
        </div>
    </div>
    <div class="content-body">
        <div class="row">
            <div class="col-xs-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Partner Chart</h4>
                        <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                                <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-body collapse in">
                        <div class="card-block">
                            @if(count($consultancies)>0)
                                <div id="column-chart"></div>
                            @else
                                <p class="card-text">No Partners Yet</p>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
   </div>
@stop

@section('js')
    <script src="https://www.google.com/jsapi" type="text/javascript"></script>

    <script src="{{asset('admin-assets/app-assets/js/scripts/charts/google/bar/column.js') }}" type="text/javascript"></script>

    <script>
        google.load('visualization', '1.0', {'packages':['corechart']});

        // Set a callback to run when the Google Visualization API is loaded.
        google.setOnLoadCallback(drawColumn);

        // Callback that creates and populates a data table, instantiates the pie chart, passes in the data and draws it.
        function drawColumn() {
            
            // Create the data table.
            var data = google.visualization.arrayToDataTable(<?php echo json_encode($consultancies) ?>);


            // Set chart options
            var options_column = {
                height: 400,
                fontSize: 12,
                colors:['#2494be','#37BC9B','#F6B75A','#e84a5f'],
                chartArea: {
                    left: '5%',
                    width: '100%',
                    height: 350
                },
                vAxis: {
                    gridlines:{
                        color: '#e9e9e9',
                        count: 10
                    },
                    minValue: 0
                },
                legend: {
                    position: 'top',
                    alignment: 'center',
                    textStyle: {
                        fontSize: 12
                    }
                }
            };

            // Instantiate and draw our chart, passing in some options.
            var bar = new google.visualization.ColumnChart(document.getElementById('column-chart'));
            bar.draw(data, options_column);

        }


        // Resize chart
        // ------------------------------

        $(function () {

            // Resize chart on menu width change and window resize
            $(window).on('resize', resize);
            $(".menu-toggle").on('click', resize);

            // Resize function
            function resize() {
                drawColumn();
            }
        });
</script>
@endsection

resources/views/admin/testimonials.blade.php
@extends('layouts.admin')

@section('body')

    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Testimonials</h2>
        </div>
    </div>
    <div class="row match-height">
        <div class="col-xl-4 col-md-6 col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-block">
                    @if($state == 'Add')
                        <form class="form" method="POST" action="{{ route('testimonials.store') }}"  enctype="multipart/form-data">
                    @else
                        <form class="form" method="POST" action="{{ route('testimonials.update',$testimonial_->id) }}"  enctype="multipart/form-data">                            
                        <input type="hidden" name="_method" value="PATCH" >
                    @endif
                            {{ csrf_field() }}
                            
                            <div class="form-group">
                                <label for="name"><strong>Name:</strong></label>
                                @if ($errors->has('name'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </div>
                                @endif
                                <input type="text" id="name" class="form-control" name="name" value="{{ $testimonial_->name }}" required/>
                            </div>

                            <div class="form-group">
                                <label for="profession"><strong>Profession:</strong></label>
                                @if ($errors->has('profession'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('profession') }}</strong>
                                    </div>
                                @endif
                                <input type="text" id="profession" class="form-control" name="profession" value="{{ $testimonial_->profession }}" required/>
                            </div>

                            <div class="form-group">
                                <label for="photo"><strong>{{ $state=='Add'?'':'Current ' }}Image <span class="text-muted">(Optional)</span>: </strong></label> {{ $testimonial_->photo }}
                                @if ($errors->has('photo'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('photo') }}</strong>
                                    </div>
                                @endif
                                <input type="file" id="photo" class="form-control" name="photo"/>
                            </div>
                            <div class="form-group">
                                <label><strong>New Testimonial:</strong></label>
                                @if ($errors->has('content'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('content') }}</strong>
                                    </div>
                                @endif
                            
                                <textarea class="form-control" rows='6' id="content" name="content" required>{{ $testimonial_->content }}</textarea>

                            </div>
                            <div class="form-actions right">
                                <button type="submit" class="btn btn-primary">
                                    <i class="icon-check2"></i> {{ $state=="Add"?"Add New":"Save" }}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @foreach($testimonials as $testimonial)
            <div class="col-xl-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="card-block">
                            <h4 class="card-title">{{ $testimonial->name }}</h4>
                            <h6 class="card-subtitle text-muted">{{ $testimonial->profession }}</h6>
                            @if($testimonial->photo)
                                <img class="img-fluid my-1" src="{{ route('optimize', ['landing_images',$testimonial->photo,290,290]) }}" alt="Card image cap">
                            @else
                                <img class="img-fluid my-1" src="/admin-assets/img/avatar.png" alt="{{ $testimonial->name }}"/>
                            @endif
                            <p class="card-text">{{ $testimonial->content }}</p>

                            <a href="{{ route('testimonials.edit',$testimonial->id) }}" class="btn btn-outline btn-warning">Edit</a>
                            
                            <form action="{{ route('testimonials.destroy',$testimonial->id) }}" style="display:inline" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE" >
                                <button id='deleteTestimonial' type="button" class="btn btn-outline btn-danger">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection