routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/how-it-works', 'HomeController@about');
Route::get('/become-a-partner', 'HomeController@becomePartner');
Route::post('/partnership-submission','HomeController@partnershipSubmission');
Route::get('/partner/{alias}','HomeController@partner');


Route::get('/profile','Frontend\UserController@index')->name('user.profile');
Route::get('/cprofile/referal','Frontend\Consultancy\ConsultancyController@referal');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/test', 'HomeController@index');

Route::post('/subscribe','HomeController@subscribe')->name('subscribe');
Route::get('unsubscribe/{token}','HomeController@unsubscribe')->name('unsubscribe');
Route::post('unsubscribe/{token}','HomeController@unsubscribed')->name('unsubscribed');

Route::get('/contact-us', 'HomeController@contactPage')->name('contact-us');
Route::post('/contact-us','HomeController@contactUs');

Route::get('/notifications','HomeController@notifications');

Route::prefix('consultancy')->group(function(){
    Route::get('/login','Frontend\Consultancy\Auth\LoginController@showLoginForm')->name('consultancy_login');
	Route::post('/login','Frontend\Consultancy\Auth\LoginController@login');
	Route::post('/logout','Frontend\Consultancy\Auth\LoginController@logout')->name('consultancy_logout');
	Route::post('/password/email','Frontend\Consultancy\Auth\ForgotPasswordController@sendResetLinkEmail')->name('consultancy_password.email');
	Route::post('/password/reset','Frontend\Consultancy\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Frontend\Consultancy\Auth\ForgotPasswordController@showLinkRequestForm')->name('consultancy_password.request');
	Route::get('/password/reset/{token}','Frontend\Consultancy\Auth\ResetPasswordController@showResetForm')->name('consultancy_password.reset');
    
    // Route::get('profile','Frontend\Consultancy\ProfileController@index');
    // Route::post('profile/changePassword','Frontend\Consultancy\ProfileController@changePassword')->name('consultancy.changePassword');
    // Route::post('profile/changeName','Frontend\Consultancy\ProfileController@updateName')->name('consultancy.updateName');

    Route::get('/cprofile','Frontend\Consultancy\ConsultancyController@index')->name('consultancy.profile');
    Route::get('/editprofile','Frontend\Consultancy\ConsultancyController@editProfile');
    Route::post('changepassword','Frontend\Consultancy\ConsultancyController@changePassword')->name('consultancy.changePassword');
   
    Route::get('/cprofile/referal','Frontend\Consultancy\ConsultancyController@referal');  
    Route::post('/referal/togglestatus','Frontend\Consultancy\ConsultancyController@toggleStatus');  
    Route::post('/referal/submitreceipt','Frontend\Consultancy\ConsultancyController@submitReceipt');  
          
    Route::get('/dashboard','Frontend\Consultancy\ConsultancyController@dashboard');
    Route::post('/dashboard/savecommission','Frontend\Consultancy\ConsultancyController@saveCommission');
    Route::post('/dashboard/toggleshowrate','Frontend\Consultancy\ConsultancyController@toggleShowRate');
    
    
    
});

Route::prefix('user')->group(function(){
    Auth::routes();
    Route::get('/register/getEmail',function(){
        return redirect('user/login');
    });

    Route::get('/editprofile','Frontend\UserController@editProfile');
    
    
    Route::post('/register/getEmail','Auth\RegisterController@setEmail')->name('set_email');
    Route::get('confirm/resend','Auth\RegisterController@resendConfirmation')->name('resend_confirmation');
    Route::get('confirm/{token}','Auth\RegisterController@confirmEmail')->name('confirmEmail');

    // Route::get('/profile','Frontend\UserController@index')->name('user.profile');

    Route::post('/changeprofilepicture','Frontend\UserController@changeProfilePicture');
    Route::get('/getreferal','Frontend\UserController@getReferal');    
    Route::post('/submitreferal','Frontend\UserController@submitReferal');
    Route::post('/savereferal','Frontend\UserController@saveReferal');
    Route::post('/submitreferaledit','Frontend\UserController@submitEditedReferal');
    Route::post('/savereferaledit','Frontend\UserController@saveEditedReferal');
    Route::post('/deletereferal','Frontend\UserController@deleteReferal');
    Route::post('/saveinfo','Frontend\UserController@saveInfo');
    Route::get('/getcommission','Frontend\UserController@getCommission');    
    Route::post('profile/changepassword','Frontend\UserController@changePassword')->name('user.changePassword');
});
Route::get('signin/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('signin/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::resource('categories', 'Admin\CategoryController',['except' => ['create','edit','show']]);

    Route::resource('partners', 'Admin\PartnerController',['except' => ['create','show']]);

    Route::resource('partners/{partner_id}/branches', 'Admin\BranchController',['except' => ['create','show']]);

    Route::get('users','Admin\UserController@index')->name('users.index');

    Route::get('referals','Admin\ReferalController@index')->name('referals.index');
    Route::post('referals/verifyreceipt','Admin\ReferalController@verifyReceipt');
    Route::post('referals/rejectreceipt','Admin\ReferalController@rejectReceipt');
    Route::post('referals/markaspaid','Admin\ReferalController@markAsPaid');
    

    // Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    // Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    // Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    // Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    // Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    // Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    // Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    // Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

    Route::get('partnerships/unseen','Admin\PartnershipController@unseenMsg')->name('partnerships.unseen');    
    Route::resource('partnerships', 'Admin\PartnershipController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenPartnershipsCount','Admin\PartnershipController@getUnseenMsgCount')->name('getUnseenPartnershipCount');
    Route::get('getUnseenPartnershipsMsg','Admin\PartnershipController@getUnseenMsg')->name('getUnseenPartnership');

    Route::get('getUnseenNotificationCount','Admin\NotificationController@getUnseenMsgCount')->name('getUnseenNotificationCount');
    Route::get('getUnseenNotificationMsg','Admin\NotificationController@getUnseenMsg')->name('getUnseenNotification');
    Route::get('/notifications/view','Admin\NotificationController@viewNotification');
    Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');
    // Route::post('test','Admin\AdminController@test')->name('test');

    Route::get('/','Admin\AdminController@index');
});

Route::get('/asset/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    $ext = explode(".",$img);
    $ext = end($ext);

app/Branch.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
    protected $fillable = ['name', 'location','lat','long','contact_email','contact_number','office_hours'];

    public function partner()
    {
        return $this->belongsTo('App\Partner');
    }

    public function staffs()
    {
        return $this->hasMany('App\Staff');
    }

    public function referal_list()
    {
        return $this->hasMany('App\Referal');
    }

    public function getFullNameAttribute(){
        return $this->partner->name.' ('.$this->attributes['name'].')';
    }

    public function getEmailAttribute(){
        return $this->staffs()->where('role','Admin')->first()->email;
    }
    
    public function notifications()
    {
        return $this->morphMany('App\Notification', 'notifiable');
    }
}

app/Referal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Consultancy;

class Referal extends Model
{
    public $appends=['consultancy_name'];
    public function getConsultancyNameAttribute()
    {
        if($this->consultancy_id!=null)
        {
            return Consultancy::findOrFail($this->consultancy_id)->name;
        }
        else
            return '';
    }
    
    public function user()
    {
        return $this->belongsTo('App\User');
    }
    
    public function branch()
    {
        return $this->belongsTo('App\Branch');
    }
}

app/Http/Controllers/Admin/ReferalController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Referal;
use App\Notification;
use Redirect;

class ReferalController extends Controller
{
    public function __construct(Request $request)
    {
        $this->middleware('auth:admin_user');
    }

    public function index()
    {
        $referals=Referal::where('status','success')->orderBy('paid_status','desc')->paginate(10);
        return view('admin.referals.index',compact('referals'));
    }
    public function verifyReceipt(Request $request)
    {

        Referal::where('id',$request->id)->update(['paid_status'=>'verified']);
        $referal = Referal::findOrFail($request->id);
        Notification::add('Your commission payment of '.$referal->name.' has been accepted ','App\Branch',$referal->branch->id,'/cprofile/referal?referal_id='.$referal->id);

        $request->session()->flash('success', 'Verified Successfully.'); 
        return Redirect::to('/admin/referals');
    }

    public function rejectReceipt(Request $request)
    {
        
        
        Referal::where('id',$request->id)->update(['paid_status'=>'rebound']);
        $referal = Referal::findOrFail($request->id);

        Notification::add('Your commission payment of '.$referal->name.' has been rejected ','App\Branch',$referal->branch->id,'/cprofile/referal?referal_id='.$referal->id);
           
        $request->session()->flash('success', 'Rejected Successfully.'); 
        return Redirect::to('/admin/referals');
    }

    public function markAsPaid(Request $request)
    {
        Referal::where('id',$request->id)->update(['status'=>'paid']);
   
        $referal = Referal::findOrFail($request->id);

        Notification::add('Commission is paid to you for your referal of '.$referal->name,'App\User',$referal->user->id,'/profile');
        
        $request->session()->flash('success', 'Mark as Paid Successfully.'); 
        return Redirect::to('/admin/referals');
    }
}

resources/views/admin/referals/index.blade.php
@extends('layouts.admin')

@section('body')
   <style>
       .table th, .table td {
     padding: 1rem 1rem; 
}
       </style>
   <div class="content-header row">
   </div>
   <div class="content-body">
       
       <div class="card">
           <div class="card-header">
               <h4 class="card-title">Successful referals</h4>
               <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
               <div class="heading-elements">
                   <ul class="list-inline mb-0">
                       <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                       <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                   </ul>
               </div>
           </div>
           <div class="card-body collapse in">
               <div class="card-block card-dashboard">
                   <div class="table-responsive">
                       <table class="table">
                           <thead>
                               <tr>
                                   <th>Referal Id</th>
                                   <th>Partner</th>
                                   <th>Refered By:</th>
                                   <th>Referal Status</th>
                                   <th>Paid Status</th>
                                   <th>Receipt</th>
                                   <th width="20%">Actions</th>
                               </tr>
                           </thead>
                           <tbody>
                               @foreach($referals as $referal)
                               <tr>
                                   <td>{{ $referal->id }}</td>
                                   <td>{{ $referal->branch->full_name }}</td>
                                   
                                   <td>
                                           {{-- <div class="tag tag-info" style="margin:2px">{{ $role->title }}</div> --}}
                                       
                                        <table>
                                            <tr> 
                                                <td>
                                                        @if($referal->user->photo!=null)
                                                            <img src="/profile_images/{{ $referal->user->photo }}" style="height:50px;width:50px;border-radius:50%;"/>
                                                        @endif
                                                </td>
                                                <td>
                                                    <p>Name: {{$referal->user->name}}</p>
                                                    <p>Email: {{$referal->user->email}}</p>
                                                    <p>Bank: {{$referal->user->bank_name}}</p>
                                                    <p>AC no: {{$referal->user->bank_account_number}}</p>
                                                    
                                                </td>
                                            </tr>
                                        </table>
                                       
                                    </td>
                                    <td>{{$referal->status}}</td>
                                    <td>{{$referal->paid_status}}</td>
                                    <td>
                                        @if($referal->receipt!=null)
                                            <img src="/receipt_images/{{ $referal->receipt }}" style="height:50px;width:50px;"/>
                                        @endif
                                    </td>
                                    
                                   <td>
                                       @if($referal->paid_status=='unverified' || $referal->paid_status=='rebound')
                                   <a href="#!" id="verifyReferalBtn{{$referal->id}}" verifyId="{{$referal->id}}" class="btn btn-success" title="Verify Payment" data-toggle="modal" data-target="#verifyConfirmation"><i class="icon-check" style="color:white"></i></a>
                                   <a href="#!" id="rejectReferalBtn{{$referal->id}}" verifyId="{{$referal->id}}" class="btn btn-danger" title="Reject Verification" data-toggle="modal" data-target="#rejectConfirmation"><i class="icon-times" style="color:white"></i></a>
                                       
                                   @endif
                                       @if($referal->receipt!=null)
                                        <a href="/receipt_images/{{$referal->receipt}}" target="_blank" id="viewReceipt" class="btn btn-primary" title="Download Receipt"><i class="icon-download"></i></a>
                                       @endif
                                       @if($referal->status=='success')
                                        <a href="#!" id="markAsPaidBtn{{$referal->id}}" verifyId="{{$referal->id}}"  class="btn btn-primary" title="Mark as Paid" data-toggle="modal" data-target="#markAsPaidConfirmation"><i class="icon-check"></i></a>
                                       @endif
                                       {{-- <form action="{{ route('referals.destroy',$referal->id) }}" method="POST" style="display:inline">
                                           {{ csrf_field() }}
                                           <input type="hidden" name="page" value="{{$referals->currentPage()}}"/>
                                           <button id='deletereferal' type="button" class="btn btn-outline-danger"><i class="icon-trash-o"></i></button>
                                       </form> --}}
                                   </td>
                               </tr>
                               @endforeach
                           </tbody>
                       </table>


                       <div class="text-xs-center mb-3">
                           <nav aria-label="Page navigation">
                               {{ $referals->links('admin.partials.pagination') }}
                           </nav>
                       </div>
                   </div>
               </div>
               <div class="modal fade text-xs-left" id="verifyConfirmation" role="dialog" aria-labelledby="myModalLabel5" aria-hidden="true" >
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                                <div class="modal-body">
                                  <h4>Is it verified??</h4>
                                  <p>Consultancy will be notified about this verification.</p>

                                </div>
                                <div class="modal-footer">
                                    <form class="form" id="consultancyEditForm" method="POST" action="/admin/referals/verifyreceipt">
                                        {{csrf_field()}}
                                        <input type="text" hidden id="verify_id" name="id" value="0"/>
                                        <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-outline-primary">Verify</button>
                                    </form> 
                                </div>
                                                              
                        </div>
                    </div>
                </div>
                <div class="modal fade text-xs-left" id="markAsPaidConfirmation" role="dialog" aria-labelledby="myModalLabel5" aria-hidden="true" >
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                                <div class="modal-body">
                                  <h4>Is it Paid??</h4>
                                  <p>User will be notified about this verification. Status of referal will be set to 'Paid'</p>

                                </div>
                                <div class="modal-footer">
                                    <form class="form" id="consultancyEditForm" method="POST" action="/admin/referals/markaspaid">
                                        {{csrf_field()}}
                                        <input type="text" hidden id="markAsPaid_id" name="id" value="0"/>
                                        <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-outline-primary">Mark as Paid</button>
                                    </form> 
                                </div>
                                                              
                        </div>
                    </div>
                </div>
                <div class="modal fade text-xs-left" id="rejectConfirmation" role="dialog" aria-labelledby="myModalLabel5" aria-hidden="true" >
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                    <div class="modal-body">
                                      <h4>Are you sure??</h4>
                                      <p>Consultancy will be notified about this rejection.</p>
    
                                    </div>
                                    <div class="modal-footer">
                                        <form class="form" id="rejectform" method="POST" action="/admin/referals/rejectreceipt">
                                            {{csrf_field()}}
                                            <input type="text" hidden id="reject_id" name="id" value="0"/>
                                            <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-outline-danger">Reject</button>
                                        </form> 
                                    </div>
                                                                  
                            </div>
                        </div>
                    </div>
               
           </div>
       </div>
   </div>

   
@endsection

@section('js')
   
       <script>
           $(document).ready(function(){
                $('[id*="verifyReferalBtn"]').click(function(){
                    console.log($(this).attr('verifyId'));
                    $('#verify_id').val($(this).attr('verifyId'));
                });
                $('[id*="rejectReferalBtn"]').click(function(){
                    console.log($(this).attr('verifyId'));
                    $('#reject_id').val($(this).attr('verifyId'));
                });
                $('[id*="markAsPaidBtn"]').click(function(){
                    console.log($(this).attr('verifyId'));
                    $('#markAsPaid_id').val($(this).attr('verifyId'));
                });
           });
        </script>

   
@endsection